INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 1, 1);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 2, 2);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 3, 3);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 4, 4);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 5, 5);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 6, 6);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 7, 7);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 8, 8);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 9, 9);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 10, 10);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 11, 11);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 12, 12);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 13, 13);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 14, 14);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 15, 15);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 16, 16);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 17, 17);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 18, 18);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 19, 19);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 20, 20);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 21, 21);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 22, 22);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 23, 23);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 24, 24);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 25, 25);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 26, 26);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 27, 27);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 28, 28);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 29, 29);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 30, 30);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 31, 31);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 32, 32);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 33, 33);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 34, 34);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 35, 35);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 36, 36);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 37, 37);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 38, 38);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 39, 39);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 40, 40);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 41, 41);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 42, 42);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 43, 43);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 44, 44);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 45, 45);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 46, 46);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 47, 47);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 48, 48);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 49, 49);
INSERT INTO activities (description, userid, forumid) VALUES ('Created a Forum Discussion Post', 50, 50);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 325, 26);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 326, 27);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 327, 28);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 328, 29);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 329, 30);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 330, 31);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 331, 32);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 332, 33);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 333, 34);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 334, 35);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 335, 36);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 336, 37);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 337, 38);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 338, 39);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 339, 40);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 340, 41);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 341, 42);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 342, 43);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 343, 44);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 344, 45);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 345, 46);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 346, 47);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 347, 48);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 348, 49);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 349, 50);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 350, 51);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 351, 52);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 352, 53);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 353, 54);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 354, 55);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 355, 56);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 356, 57);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 357, 58);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 358, 59);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 359, 60);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 360, 61);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 361, 62);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 362, 63);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 363, 64);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 364, 65);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 365, 66);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 366, 67);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 367, 68);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 368, 69);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 369, 70);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 370, 71);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 371, 72);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 372, 73);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 373, 74);
INSERT INTO activities (description, userid, likeid) VALUES ('Liked a Post', 374, 75);
