INSERT INTO dislikes (userid, commentid, forumid) VALUES (400, 26, 26);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (401, 27, 27);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (402, 28, 28);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (403, 29, 29);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (404, 30, 30);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (405, 31, 31);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (406, 32, 32);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (407, 33, 33);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (408, 34, 34);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (409, 35, 35);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (410, 36, 36);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (411, 37, 37);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (412, 38, 38);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (413, 39, 39);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (414, 40, 40);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (415, 41, 41);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (416, 42, 42);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (417, 43, 43);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (418, 44, 44);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (419, 45, 45);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (420, 46, 46);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (421, 47, 47);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (422, 48, 48);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (423, 49, 49);
INSERT INTO dislikes (userid, commentid, forumid) VALUES (424, 50, 50);
INSERT INTO dislikes (userid, commentid) VALUES (425, 1);
INSERT INTO dislikes (userid, commentid) VALUES (426, 2);
INSERT INTO dislikes (userid, commentid) VALUES (427, 3);
INSERT INTO dislikes (userid, commentid) VALUES (428, 4);
INSERT INTO dislikes (userid, commentid) VALUES (429, 5);
INSERT INTO dislikes (userid, commentid) VALUES (430, 6);
INSERT INTO dislikes (userid, commentid) VALUES (431, 7);
INSERT INTO dislikes (userid, commentid) VALUES (432, 8);
INSERT INTO dislikes (userid, commentid) VALUES (433, 9);
INSERT INTO dislikes (userid, commentid) VALUES (434, 10);
INSERT INTO dislikes (userid, commentid) VALUES (435, 11);
INSERT INTO dislikes (userid, commentid) VALUES (436, 12);
INSERT INTO dislikes (userid, commentid) VALUES (437, 13);
INSERT INTO dislikes (userid, commentid) VALUES (438, 14);
INSERT INTO dislikes (userid, commentid) VALUES (439, 15);
INSERT INTO dislikes (userid, commentid) VALUES (440, 16);
INSERT INTO dislikes (userid, commentid) VALUES (441, 17);
INSERT INTO dislikes (userid, commentid) VALUES (442, 18);
INSERT INTO dislikes (userid, commentid) VALUES (443, 19);
INSERT INTO dislikes (userid, commentid) VALUES (444, 20);
INSERT INTO dislikes (userid, commentid) VALUES (445, 21);
INSERT INTO dislikes (userid, commentid) VALUES (446, 22);
INSERT INTO dislikes (userid, commentid) VALUES (447, 23);
INSERT INTO dislikes (userid, commentid) VALUES (448, 24);
INSERT INTO dislikes (userid, commentid) VALUES (449, 25);
INSERT INTO dislikes (userid, commentid) VALUES (450, 51);
INSERT INTO dislikes (userid, commentid) VALUES (451, 52);
INSERT INTO dislikes (userid, commentid) VALUES (452, 53);
INSERT INTO dislikes (userid, commentid) VALUES (453, 54);
INSERT INTO dislikes (userid, commentid) VALUES (454, 55);
INSERT INTO dislikes (userid, commentid) VALUES (455, 56);
INSERT INTO dislikes (userid, commentid) VALUES (456, 57);
INSERT INTO dislikes (userid, commentid) VALUES (457, 58);
INSERT INTO dislikes (userid, commentid) VALUES (458, 59);
INSERT INTO dislikes (userid, commentid) VALUES (459, 60);
INSERT INTO dislikes (userid, commentid) VALUES (460, 61);
INSERT INTO dislikes (userid, commentid) VALUES (461, 62);
INSERT INTO dislikes (userid, commentid) VALUES (462, 63);
INSERT INTO dislikes (userid, commentid) VALUES (463, 64);
INSERT INTO dislikes (userid, commentid) VALUES (464, 65);
INSERT INTO dislikes (userid, commentid) VALUES (465, 66);
INSERT INTO dislikes (userid, commentid) VALUES (466, 67);
INSERT INTO dislikes (userid, commentid) VALUES (467, 68);
INSERT INTO dislikes (userid, commentid) VALUES (468, 69);
INSERT INTO dislikes (userid, commentid) VALUES (469, 70);
INSERT INTO dislikes (userid, commentid) VALUES (470, 71);
INSERT INTO dislikes (userid, commentid) VALUES (471, 72);
INSERT INTO dislikes (userid, commentid) VALUES (472, 73);
INSERT INTO dislikes (userid, commentid) VALUES (473, 74);
INSERT INTO dislikes (userid, commentid) VALUES (474, 75);
INSERT INTO dislikes (userid, commentid) VALUES (475, 76);
INSERT INTO dislikes (userid, commentid) VALUES (476, 77);
INSERT INTO dislikes (userid, commentid) VALUES (477, 78);
INSERT INTO dislikes (userid, commentid) VALUES (478, 79);
INSERT INTO dislikes (userid, commentid) VALUES (479, 80);
INSERT INTO dislikes (userid, commentid) VALUES (480, 81);
INSERT INTO dislikes (userid, commentid) VALUES (481, 82);
INSERT INTO dislikes (userid, commentid) VALUES (482, 83);
INSERT INTO dislikes (userid, commentid) VALUES (483, 84);
INSERT INTO dislikes (userid, commentid) VALUES (484, 85);
INSERT INTO dislikes (userid, commentid) VALUES (485, 86);
INSERT INTO dislikes (userid, commentid) VALUES (486, 87);
INSERT INTO dislikes (userid, commentid) VALUES (487, 88);
INSERT INTO dislikes (userid, commentid) VALUES (488, 89);
INSERT INTO dislikes (userid, commentid) VALUES (489, 90);
INSERT INTO dislikes (userid, commentid) VALUES (490, 91);
INSERT INTO dislikes (userid, commentid) VALUES (491, 92);
INSERT INTO dislikes (userid, commentid) VALUES (492, 93);
INSERT INTO dislikes (userid, commentid) VALUES (493, 94);
INSERT INTO dislikes (userid, commentid) VALUES (494, 95);
INSERT INTO dislikes (userid, commentid) VALUES (495, 96);
INSERT INTO dislikes (userid, commentid) VALUES (496, 97);
INSERT INTO dislikes (userid, commentid) VALUES (497, 98);
INSERT INTO dislikes (userid, commentid) VALUES (498, 99);
INSERT INTO dislikes (userid, commentid) VALUES (499, 100);