INSERT INTO likes (userid, commentid, forumid) VALUES (300, 26, 26);
INSERT INTO likes (userid, commentid, forumid) VALUES (301, 27, 27);
INSERT INTO likes (userid, commentid, forumid) VALUES (302, 28, 28);
INSERT INTO likes (userid, commentid, forumid) VALUES (303, 29, 29);
INSERT INTO likes (userid, commentid, forumid) VALUES (304, 30, 30);
INSERT INTO likes (userid, commentid, forumid) VALUES (305, 31, 31);
INSERT INTO likes (userid, commentid, forumid) VALUES (306, 32, 32);
INSERT INTO likes (userid, commentid, forumid) VALUES (307, 33, 33);
INSERT INTO likes (userid, commentid, forumid) VALUES (308, 34, 34);
INSERT INTO likes (userid, commentid, forumid) VALUES (309, 35, 35);
INSERT INTO likes (userid, commentid, forumid) VALUES (310, 36, 36);
INSERT INTO likes (userid, commentid, forumid) VALUES (311, 37, 37);
INSERT INTO likes (userid, commentid, forumid) VALUES (312, 38, 38);
INSERT INTO likes (userid, commentid, forumid) VALUES (313, 39, 39);
INSERT INTO likes (userid, commentid, forumid) VALUES (314, 40, 40);
INSERT INTO likes (userid, commentid, forumid) VALUES (315, 41, 41);
INSERT INTO likes (userid, commentid, forumid) VALUES (316, 42, 42);
INSERT INTO likes (userid, commentid, forumid) VALUES (317, 43, 43);
INSERT INTO likes (userid, commentid, forumid) VALUES (318, 44, 44);
INSERT INTO likes (userid, commentid, forumid) VALUES (319, 45, 45);
INSERT INTO likes (userid, commentid, forumid) VALUES (320, 46, 46);
INSERT INTO likes (userid, commentid, forumid) VALUES (321, 47, 47);
INSERT INTO likes (userid, commentid, forumid) VALUES (322, 48, 48);
INSERT INTO likes (userid, commentid, forumid) VALUES (323, 49, 49);
INSERT INTO likes (userid, commentid, forumid) VALUES (324, 50, 50);
INSERT INTO likes (userid, commentid) VALUES (325, 1);
INSERT INTO likes (userid, commentid) VALUES (326, 2);
INSERT INTO likes (userid, commentid) VALUES (327, 3);
INSERT INTO likes (userid, commentid) VALUES (328, 4);
INSERT INTO likes (userid, commentid) VALUES (329, 5);
INSERT INTO likes (userid, commentid) VALUES (330, 6);
INSERT INTO likes (userid, commentid) VALUES (331, 7);
INSERT INTO likes (userid, commentid) VALUES (332, 8);
INSERT INTO likes (userid, commentid) VALUES (333, 9);
INSERT INTO likes (userid, commentid) VALUES (334, 10);
INSERT INTO likes (userid, commentid) VALUES (335, 11);
INSERT INTO likes (userid, commentid) VALUES (336, 12);
INSERT INTO likes (userid, commentid) VALUES (337, 13);
INSERT INTO likes (userid, commentid) VALUES (338, 14);
INSERT INTO likes (userid, commentid) VALUES (339, 15);
INSERT INTO likes (userid, commentid) VALUES (340, 16);
INSERT INTO likes (userid, commentid) VALUES (341, 17);
INSERT INTO likes (userid, commentid) VALUES (342, 18);
INSERT INTO likes (userid, commentid) VALUES (343, 19);
INSERT INTO likes (userid, commentid) VALUES (344, 20);
INSERT INTO likes (userid, commentid) VALUES (345, 21);
INSERT INTO likes (userid, commentid) VALUES (346, 22);
INSERT INTO likes (userid, commentid) VALUES (347, 23);
INSERT INTO likes (userid, commentid) VALUES (348, 24);
INSERT INTO likes (userid, commentid) VALUES (349, 25);
INSERT INTO likes (userid, commentid) VALUES (350, 51);
INSERT INTO likes (userid, commentid) VALUES (351, 52);
INSERT INTO likes (userid, commentid) VALUES (352, 53);
INSERT INTO likes (userid, commentid) VALUES (353, 54);
INSERT INTO likes (userid, commentid) VALUES (354, 55);
INSERT INTO likes (userid, commentid) VALUES (355, 56);
INSERT INTO likes (userid, commentid) VALUES (356, 57);
INSERT INTO likes (userid, commentid) VALUES (357, 58);
INSERT INTO likes (userid, commentid) VALUES (358, 59);
INSERT INTO likes (userid, commentid) VALUES (359, 60);
INSERT INTO likes (userid, commentid) VALUES (360, 61);
INSERT INTO likes (userid, commentid) VALUES (361, 62);
INSERT INTO likes (userid, commentid) VALUES (362, 63);
INSERT INTO likes (userid, commentid) VALUES (363, 64);
INSERT INTO likes (userid, commentid) VALUES (364, 65);
INSERT INTO likes (userid, commentid) VALUES (365, 66);
INSERT INTO likes (userid, commentid) VALUES (366, 67);
INSERT INTO likes (userid, commentid) VALUES (367, 68);
INSERT INTO likes (userid, commentid) VALUES (368, 69);
INSERT INTO likes (userid, commentid) VALUES (369, 70);
INSERT INTO likes (userid, commentid) VALUES (370, 71);
INSERT INTO likes (userid, commentid) VALUES (371, 72);
INSERT INTO likes (userid, commentid) VALUES (372, 73);
INSERT INTO likes (userid, commentid) VALUES (373, 74);
INSERT INTO likes (userid, commentid) VALUES (374, 75);
INSERT INTO likes (userid, commentid) VALUES (375, 76);
INSERT INTO likes (userid, commentid) VALUES (376, 77);
INSERT INTO likes (userid, commentid) VALUES (377, 78);
INSERT INTO likes (userid, commentid) VALUES (378, 79);
INSERT INTO likes (userid, commentid) VALUES (379, 80);
INSERT INTO likes (userid, commentid) VALUES (380, 81);
INSERT INTO likes (userid, commentid) VALUES (381, 82);
INSERT INTO likes (userid, commentid) VALUES (382, 83);
INSERT INTO likes (userid, commentid) VALUES (383, 84);
INSERT INTO likes (userid, commentid) VALUES (384, 85);
INSERT INTO likes (userid, commentid) VALUES (385, 86);
INSERT INTO likes (userid, commentid) VALUES (386, 87);
INSERT INTO likes (userid, commentid) VALUES (387, 88);
INSERT INTO likes (userid, commentid) VALUES (388, 89);
INSERT INTO likes (userid, commentid) VALUES (389, 90);
INSERT INTO likes (userid, commentid) VALUES (390, 91);
INSERT INTO likes (userid, commentid) VALUES (391, 92);
INSERT INTO likes (userid, commentid) VALUES (392, 93);
INSERT INTO likes (userid, commentid) VALUES (393, 94);
INSERT INTO likes (userid, commentid) VALUES (394, 95);
INSERT INTO likes (userid, commentid) VALUES (395, 96);
INSERT INTO likes (userid, commentid) VALUES (396, 97);
INSERT INTO likes (userid, commentid) VALUES (397, 98);
INSERT INTO likes (userid, commentid) VALUES (398, 99);
INSERT INTO likes (userid, commentid) VALUES (399, 100);